export const DATE_DISPLAY_FORMAT = "MM/DD/YYYY";
export const DATE_STORAGE_FORMAT = "YYYY-MM-DD";
export const LOCAL_DEMO_DATA = [
  {
    date: "01/02/2024",
    balance: 4180,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4080,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 100,
      expenses: [
        {
          name: "Hobbies",
          amount: 100,
          repeated: "Weekly",
        },
      ],
    },
  },
  {
    date: "01/03/2024",
    balance: 4180,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/04/2024",
    balance: 4180,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/05/2024",
    balance: 4180,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/06/2024",
    balance: 4180,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/07/2024",
    balance: 4180,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/08/2024",
    balance: 4080,
    balanceDetails: {
      previousBalance: 4180,
      newBalance: 4080,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 100,
      expenses: [
        {
          name: "Cell Phone",
          amount: 100,
          repeated: "monthly",
        },
      ],
    },
  },
  {
    date: "01/09/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 4080,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 300,
      expenses: [
        {
          name: "Hobbies",
          amount: 100,
          repeated: "Weekly",
        },
        {
          name: "Food",
          amount: 200,
          repeated: "Weekly",
        },
      ],
    },
  },
  {
    date: "01/10/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/11/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/12/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/13/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/14/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/15/2024",
    balance: 3780,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3780,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/16/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3780,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 300,
      expenses: [
        {
          name: "Hobbies",
          amount: 100,
          repeated: "Weekly",
        },
        {
          name: "Food",
          amount: 200,
          repeated: "Weekly",
        },
      ],
    },
  },
  {
    date: "01/17/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/18/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/19/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/20/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/21/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/22/2024",
    balance: 3480,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3480,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/23/2024",
    balance: 3180,
    balanceDetails: {
      previousBalance: 3480,
      newBalance: 3180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 300,
      expenses: [
        {
          name: "Hobbies",
          amount: 100,
          repeated: "Weekly",
        },
        {
          name: "Food",
          amount: 200,
          repeated: "Weekly",
        },
      ],
    },
  },
  {
    date: "01/24/2024",
    balance: 3180,
    balanceDetails: {
      previousBalance: 3180,
      newBalance: 3180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/25/2024",
    balance: 3180,
    balanceDetails: {
      previousBalance: 3180,
      newBalance: 3180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/26/2024",
    balance: 3180,
    balanceDetails: {
      previousBalance: 3180,
      newBalance: 3180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/27/2024",
    balance: 7180,
    balanceDetails: {
      previousBalance: 3180,
      newBalance: 7180,
      incomesTotal: 4000,
      incomes: [
        {
          name: "Test Income",
          amount: 4000,
          repeated: "Biweekly",
        },
      ],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/28/2024",
    balance: 7180,
    balanceDetails: {
      previousBalance: 7180,
      newBalance: 7180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/29/2024",
    balance: 7180,
    balanceDetails: {
      previousBalance: 7180,
      newBalance: 7180,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 0,
      expenses: [],
    },
  },
  {
    date: "01/30/2024",
    balance: 6880,
    balanceDetails: {
      previousBalance: 7180,
      newBalance: 6880,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 300,
      expenses: [
        {
          name: "Hobbies",
          amount: 100,
          repeated: "Weekly",
        },
        {
          name: "Food",
          amount: 200,
          repeated: "Weekly",
        },
      ],
    },
  },
  {
    date: "01/31/2024",
    balance: 6680,
    balanceDetails: {
      previousBalance: 6880,
      newBalance: 6680,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 200,
      expenses: [
        {
          name: "Electricity",
          amount: 200,
          repeated: "Monthly",
        },
      ],
    },
  },
  {
    date: "02/01/2024",
    balance: 4680,
    balanceDetails: {
      previousBalance: 6680,
      newBalance: 4680,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 2000,
      expenses: [
        {
          name: "Rent",
          amount: 2000,
          repeated: "monthly",
        },
      ],
    },
  },
];