const expectedForecast = [
  {
    date: "08/02/2023",
    balance: 1000,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/03/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/04/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/05/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/06/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/07/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/08/2023",
    balance: 1098,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 1098,
      incomesTotal: 100,
      incomes: [
        { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
      ],
      expensesTotal: 2,
      expenses: [
        { name: "Test Daily", amount: 1, repeated: "Daily" },
        { name: "Test Weekly", amount: 1, repeated: "Weekly" },
      ],
    },
  },
  {
    date: "08/09/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/10/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/11/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/12/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/13/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/14/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/15/2023",
    balance: 1097,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 1097,
      incomesTotal: 100,
      incomes: [
        { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
      ],
      expensesTotal: 3,
      expenses: [
        { name: "Test Daily", amount: 1, repeated: "Daily" },
        { name: "Test Weekly", amount: 1, repeated: "Weekly" },
        { name: "Test Biweekly", amount: 1, repeated: "Biweekly" },
      ],
    },
  },
  {
    date: "08/16/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/17/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/18/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/19/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/20/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/21/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/22/2023",
    balance: 1098,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 1098,
      incomesTotal: 100,
      incomes: [
        { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
      ],
      expensesTotal: 2,
      expenses: [
        { name: "Test Daily", amount: 1, repeated: "Daily" },
        { name: "Test Weekly", amount: 1, repeated: "Weekly" },
      ],
    },
  },
  {
    date: "08/23/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/24/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/25/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/26/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/27/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/28/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/29/2023",
    balance: 1097,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 1097,
      incomesTotal: 100,
      incomes: [
        { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
      ],
      expensesTotal: 3,
      expenses: [
        { name: "Test Daily", amount: 1, repeated: "Daily" },
        { name: "Test Weekly", amount: 1, repeated: "Weekly" },
        { name: "Test Biweekly", amount: 1, repeated: "Biweekly" },
      ],
    },
  },
  {
    date: "08/30/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
  {
    date: "08/31/2023",
    balance: 999,
    balanceDetails: {
      previousBalance: 1000,
      newBalance: 999,
      incomesTotal: 0,
      incomes: [],
      expensesTotal: 1,
      expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
    },
  },
];

export default expectedForecast;