// import dayjs from "dayjs";

// const thisMonth = dayjs().month();
// const month = dayjs(thisMonth).format("MM");

// const expectedForecast = [
//   {
//     date: `${month}/02/2023`,
//     balance: 1000,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/03/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/04/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/05/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/06/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/07/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/08/2023`,
//     balance: 1098,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 1098,
//       incomesTotal: 100,
//       incomes: [
//         { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
//       ],
//       expensesTotal: 2,
//       expenses: [
//         { name: "Test Daily", amount: 1, repeated: "Daily" },
//         { name: "Test Weekly", amount: 1, repeated: "Weekly" },
//       ],
//     },
//   },
//   {
//     date: `${month}/09/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/10/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/11/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/12/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/13/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/14/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/15/2023`,
//     balance: 1097,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 1097,
//       incomesTotal: 100,
//       incomes: [
//         { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
//       ],
//       expensesTotal: 3,
//       expenses: [
//         { name: "Test Daily", amount: 1, repeated: "Daily" },
//         { name: "Test Weekly", amount: 1, repeated: "Weekly" },
//         { name: "Test Biweekly", amount: 1, repeated: "Biweekly" },
//       ],
//     },
//   },
//   {
//     date: `${month}/16/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/17/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/18/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/19/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/20/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/21/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/22/2023`,
//     balance: 1098,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 1098,
//       incomesTotal: 100,
//       incomes: [
//         { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
//       ],
//       expensesTotal: 2,
//       expenses: [
//         { name: "Test Daily", amount: 1, repeated: "Daily" },
//         { name: "Test Weekly", amount: 1, repeated: "Weekly" },
//       ],
//     },
//   },
//   {
//     date: `${month}/23/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/24/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/25/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/26/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/27/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/28/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/29/2023`,
//     balance: 1097,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 1097,
//       incomesTotal: 100,
//       incomes: [
//         { name: "Test Income Biweekly", amount: 100, repeated: "Biweekly" },
//       ],
//       expensesTotal: 3,
//       expenses: [
//         { name: "Test Daily", amount: 1, repeated: "Daily" },
//         { name: "Test Weekly", amount: 1, repeated: "Weekly" },
//         { name: "Test Biweekly", amount: 1, repeated: "Biweekly" },
//       ],
//     },
//   },
//   {
//     date: `${month}/30/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
//   {
//     date: `${month}/31/2023`,
//     balance: 999,
//     balanceDetails: {
//       previousBalance: 1000,
//       newBalance: 999,
//       incomesTotal: 0,
//       incomes: [],
//       expensesTotal: 1,
//       expenses: [{ name: "Test Daily", amount: 1, repeated: "Daily" }],
//     },
//   },
// ];

// export default expectedForecast;
